pipeline {
    agent any
    
    stages {
        
        stage('github-clone') {
            steps {
                echo 'Hello'
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/dykim-egene/CICD.git'
            }
        }
        
   		// stage...
   	}
}
