pipeline {
    agent any
    
    stages {
        
        stage('github-clone') {
            steps {
                git branch: 'CICD', credentialsId: 'github_key', url: '{REPOSITORY URL}'
            }
        }
        
   		// stage...
   	}
}
